####  PBS preamble

#PBS -N adjgraph
#PBS -M frcheng@umich.edu
#PBS -m abe

#PBS -A wellman_flux
#PBS -l qos=flux
#PBS -q flux-oncampus

#PBS -l nodes=4:ppn=2,pmem=8gb
#PBS -l walltime=25:15:00
#PBS -j oe
#PBS -V

####  End PBS preamble

if [ -s "$PBS_NODEFILE" ] ; then
    echo "Running on"
    cat $PBS_NODEFILE
fi

if [ -d "$PBS_O_WORKDIR" ] ; then
    cd $PBS_O_WORKDIR
    echo "Running from $PBS_O_WORKDIR"
fi

#  Put your job commands after this line
module load cplex
make simCtest
