#!/bin/bash
#SBATCH --account=wellman
#SBATCH --partition=standard-oc
#SBATCH --nodes=1
#SBATCH --mem-per-cpu=8000m
#SBATCH --time=100:20:00
#SBATCH --job-name=egta-crednet_cycle
#SBATCH --mail-user=frcheng@umich.edu
#SBATCH --mail-type=BEGIN,END

# module load cplex
make simCtestp_eval